import {
    AuthAction,
    useAuthUser,
    withAuthUser,
    withAuthUserTokenSSR,
} from 'next-firebase-auth';
import firebase from 'firebase/app';
import Head from 'next/head';
import Link from 'next/link';
import React, { useState, useEffect } from 'react';
  
const Admin = () => {


return (
    <div>
      <Head>
        <title>Administración</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="all">
        <div id="cabecera">
          <div id="title_cabecera">
            <Link href="/" className="homeLink">
              Bot Trinitat Nova
            </Link>
          </div>
          <Link onClick={() => firebase.auth().signOut()} href="" id="login_cabecera">
            LOG OUT
          </Link>
        </div>
        <div id='buttons_go'>
          <div id="go_events">
            <a href='admin'>Volver</a>
          </div>
          <h1>NOM CATEGORIA</h1>
          <div>
            <table className='data'>
                <tr className='data_bold'>
                    <td colSpan='1'>Nom</td>
                    <td colSpan='2'>Información</td>
                    <td colSpan='1'>Contacto</td>
                    <td colSpan='1'>Horarios</td>
                    <td colSpan='1'>Web</td>
                    <td colSpan='1'>Dirección</td>
                </tr>
                <tr>
                    <td colSpan='1'>Nom</td>
                    <td colSpan='2'>Información</td>
                    <td colSpan='1'>Contacto</td>
                    <td colSpan='1'>Horarios</td>
                    <td colSpan='1'>Web</td>
                    <td colSpan='1'>Dirección</td>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

// Note that this is a higher-order function.
export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})(() => {
  return {
    props: {}
  }
})

export default withAuthUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN
})(Admin)