import {
    AuthAction,
    useAuthUser,
    withAuthUser,
    withAuthUserTokenSSR,
  } from 'next-firebase-auth';
  import firebase from 'firebase/app';
  import Head from 'next/head';
  import Link from 'next/link';
  
  // <p>Your email is {AuthUser.email ? AuthUser.email : 'unknown'}.</p>
  //
  
  const editCat = (event) => {
    let input = prompt("Nom de la categoria:");
    if (input == null || input == "") {
      input = "User cancelled the prompt.";
    }
    console.log(input)
  }
  
  const Demo = () => {
    const AuthUser = useAuthUser()
    return (
        <div>
            <Head>
                <title>Creación</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <div id="all">
            <div id="form_body">
                <div id="form-div">
                    <form>
                        <input type="text" id="title_noticia" name="titular" className='title_noticia' placeholder="Titular..."/>
                        <textarea type="text" id="text_noticia" name="infor" className='text_noticia' rows="10" placeholder="Información..."></textarea>
                        <img src=""/>
                        <input type="image" id="image_add" alt="Añadir imagen" src="/media/examples/login-button.png"/>
                        <input type="submit" id='add-button' value="Añadir"/>
                    </form>
                    <div id='atras_div'>
                        <Link className='atras_button' href="events">Atras</Link>  
                    </div>
                </div>
            </div>
        </div>
    </div>
    )
  }
  
  // Note that this is a higher-order function.
  export const getServerSideProps = withAuthUserTokenSSR({
    whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
  })(() => {
    return {
      props: {}
    }
  })
  
  export default withAuthUser({
    whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN
  })(Demo)
