import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useRef, useState } from "react";

export default function Home() {

  const [displayNoticias, setDisplayNoticias] = useState(true)
  const [displayEventos, setDisplayEventos] = useState(false)

  const handleBtnDivnClick = () => {
    setDisplayNoticias(true);
    setDisplayEventos(false);
  }

  const handleBtnDiveClick = () => {
    setDisplayNoticias(false);
    setDisplayEventos(true);
  }

  const [rows, setRows] = useState([]);

  const getRows = async () => {
    try {
      const res = await fetch(`https://bottn.glitch.me/api/events/${displayNoticias}`, {
        method: 'GET',
        headers: new Headers({ 'Content-type': 'application/json' }),
        mode: 'cors'
      });
      console.log(res)
      const data = await res.json();

      const formattedData = data.map(({ id, titulo, informacion, links }) => ({ id, titulo, informacion, links }));
      setRows(formattedData);
    } catch (err) {
      console.log(err);
    }
  };

  useEffect(() => {
    getRows();
    console.log(rows)
  }, [displayNoticias, displayEventos]);

  const TableTR = () => ({
    renderRow(props) {
      return (
        <div>
          <h1>{props.titulo}</h1>
          <p>{props.informacion}</p>
          <p><Link href={props.links}>{props.links}</Link></p>
        </div>
      );
    },

    render: function () {
      return (
        <div>
          {this.props.rows.map(this.renderRow)}
        </div>
      );
    }
  });

  

  useEffect(() => {
    const modal = document.getElementById("myModal");
    const btn = document.getElementById("myBtn");
    const span = document.getElementsByClassName("close")[0];

    const handleBtnClick = () => {
      modal.style.display = "block";
    }

    const handleCloseClick = () => {
      modal.style.display = "none";
    }

    const handleWindowClick = (event) => {
      if (event.target === modal) {
        modal.style.display = "none";
      }
    }

    btn.addEventListener('click', handleBtnClick);
    span.addEventListener('click', handleCloseClick);
    window.addEventListener('click', handleWindowClick);

    return () => {
      btn.removeEventListener('click', handleBtnClick);
      span.removeEventListener('click', handleCloseClick);
      window.removeEventListener('click', handleWindowClick);
    };

  }, 
  
  []);

  return (
    <>
      <Head>
        <title>BOT TN</title>
        <meta charset="UTF-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="all">
        <div id="cabecera">
          <div id="title_cabecera">
            <a href="/" className="homeLink">
              Bot Trinitat Nova
            </a>
          </div>
        </div>
        <div id="cuerpo">
          <div id="qr">
            <Link href="" id="myBtn">Instrucciones</Link>
            <div id="myModal" className="modal">
              <div className="modal-content">
                <span className="close">&times;</span>
                <p>titulo = vuelta menu <br /> botnoes = cambio eventos</p>
              </div>
            </div>
            <Link id="date_user" href="/date_user">Calendario</Link>
            <div id="myModal" className="modal">
              <div className="modal-content">
                <span className="close">
                  &times;
                </span>
                <p>Instrucciones de cómo funciona la página web</p>
              </div>
            </div>
            <img id="qr_img" src="/QR.png" />
            <a href="https://wa.me/message/E5USRNWNH4VBL1">
              <button id="qr_button">
                WhatsApp Bot
              </button>
            </a>
          </div>
          <div id="eventos2">
            <div id="seleccion">
              <Link href="" className="btn_divg" onClick={handleBtnDivnClick}>Noticias</Link>
              <Link href="" className="btn_divg" onClick={handleBtnDiveClick}>Agenda</Link>
            </div>
            <div id="block">
              <div className="div_noticias" id="div_noticias" style={{ display: displayNoticias ? 'block' : 'none' }}>
                {rows.length > 0 ? <TableTR rows={rows} /> : <p>Loading...</p>}
              </div>
              <div className="div_eventos" id="div_eventos" style={{ display: displayEventos ? 'block' : 'none' }}>
                {rows.length > 0 ? <TableTR rows={rows} /> : <p>Loading...</p>}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}