import Head from 'next/head'
import Link from 'next/link'

//<input id="buscador_cabecera" type="text" placeholder="Buscar...">

export default function Home() {
  return (
    <>
      <Head>
        <title>Bot Trinitat Nova</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="all">
        <div id="cabecera">
            <div id="title_cabecera">
              <a href="/" className="homeLink">
                Bot Trinitat Nova
              </a>
            </div>
        </div>
        <div id="cuerpo">
            <div id="enlaces">
                <ul>
                    <li><a href="/info">tables</a></li>
                </ul>
            </div>
            <div id="eventos">
                <div className="evento">
                    hola
                </div>
            </div>
            <div id="qr">
                <img id="qr_img" src="QR.png"/>
                <a href="https://wa.me/message/E5USRNWNH4VBL1">
                    <button id="qr_button">
                        WhatsApp Bot
                    </button>
                </a>
            </div>
        </div>
        <div className="footer-basic">
          <footer>
              <div>
                <a href="#">Condiciones de uso</a>
                <a href="#">Políticas de privacidad</a>
                <a href="#">Políticas de cookies</a>
                <a href="#">Accesibildad</a>
              </div>
          </footer>
        </div>
    </div>
    </>
  )
}
