import {
  AuthAction,
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
} from 'next-firebase-auth';
import firebase from 'firebase/app';
import Head from 'next/head';
import Link from 'next/link';
import FormData from 'form-data';
import { useState, useRef } from "react";

// <p>Your email is {AuthUser.email ? AuthUser.email : 'unknown'}.</p>
//

const Demo = () => {
  const AuthUser = useAuthUser()

  const [opcionSeleccionada, setOpcionSeleccionada] = useState('Eventos');

  const handleChange = (e) => {
    setOpcionSeleccionada(e.target.value);
  };

  const uploadImage = (event) => {
    console.log(event.target)
    const file = event.target.files[0];
    const data = new FormData();
    data.append('image', file);

    
  };

  return (
    <div>
      <Head>
        <title>Creación</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="all">
        <img src="#" id="img" height="200px" />
        <br />
        <input type="file" id="file" /* onChange={ (e) => uploadImage} */ />
        <br />
        <p id="url"></p>
        <button onClick={uploadImage}>upload</button>
      </div>
    </div>
  )
}

export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})(() => {
  return {
    props: {}
  }
})

export default withAuthUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN
})(Demo)
